config:
  use_colors: true
default:
  outputs:
    dev:
      dbname: nyc_taxi
      host: 111.118.241.68
      pass: 47Billion
      port: 5431
      schema: nyc_taxi_schema
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: nyc_taxi
      host: 111.118.241.68
      pass: 47Billion
      port: 5431
      schema: analytics
      threads: 1
      type: postgres
      user: postgres
  target: dev
